// Generated by gencpp from file encoder_measure/Encoder.msg
// DO NOT EDIT!


#ifndef ENCODER_MEASURE_MESSAGE_ENCODER_H
#define ENCODER_MEASURE_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace encoder_measure
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , left_encoder_count(0.0)
    , right_encoder_count(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_encoder_count(0.0)
    , right_encoder_count(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_encoder_count_type;
  _left_encoder_count_type left_encoder_count;

   typedef float _right_encoder_count_type;
  _right_encoder_count_type right_encoder_count;




  typedef boost::shared_ptr< ::encoder_measure::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::encoder_measure::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::encoder_measure::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::encoder_measure::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::encoder_measure::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::encoder_measure::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::encoder_measure::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace encoder_measure

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'encoder_measure': ['/home/administrator/catkin_ws/src/encoder_measure/msg'], 'jackal_msgs': ['/opt/ros/indigo/share/jackal_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::encoder_measure::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::encoder_measure::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::encoder_measure::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::encoder_measure::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder_measure::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder_measure::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::encoder_measure::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07ec1d6cb22ae20bf18fc2656c828ce1";
  }

  static const char* value(const ::encoder_measure::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07ec1d6cb22ae20bULL;
  static const uint64_t static_value2 = 0xf18fc2656c828ce1ULL;
};

template<class ContainerAllocator>
struct DataType< ::encoder_measure::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "encoder_measure/Encoder";
  }

  static const char* value(const ::encoder_measure::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::encoder_measure::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 left_encoder_count\n\
float32 right_encoder_count\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::encoder_measure::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::encoder_measure::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_encoder_count);
      stream.next(m.right_encoder_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::encoder_measure::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::encoder_measure::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_encoder_count: ";
    Printer<float>::stream(s, indent + "  ", v.left_encoder_count);
    s << indent << "right_encoder_count: ";
    Printer<float>::stream(s, indent + "  ", v.right_encoder_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENCODER_MEASURE_MESSAGE_ENCODER_H
