(cl:defpackage vicon_bridge-srv
  (:use )
  (:export
   "VICONGRABPOSE"
   "<VICONGRABPOSE-REQUEST>"
   "VICONGRABPOSE-REQUEST"
   "<VICONGRABPOSE-RESPONSE>"
   "VICONGRABPOSE-RESPONSE"
   "VICONCALIBRATESEGMENT"
   "<VICONCALIBRATESEGMENT-REQUEST>"
   "VICONCALIBRATESEGMENT-REQUEST"
   "<VICONCALIBRATESEGMENT-RESPONSE>"
   "VICONCALIBRATESEGMENT-RESPONSE"
  ))

