(cl:defpackage map_merger-srv
  (:use )
  (:export
   "TRANSFORMPOINT"
   "<TRANSFORMPOINT-REQUEST>"
   "TRANSFORMPOINT-REQUEST"
   "<TRANSFORMPOINT-RESPONSE>"
   "TRANSFORMPOINT-RESPONSE"
   "LOGMAPS"
   "<LOGMAPS-REQUEST>"
   "LOGMAPS-REQUEST"
   "<LOGMAPS-RESPONSE>"
   "LOGMAPS-RESPONSE"
  ))

